#!/bin/sh
#***********************************************************************
#
# pppoe-status
#
# Shell script to report on status of PPPoE connection
#
# Copyright (C) 2000-2001 Roaring Penguin Software Inc.
#
# $Id$
#
# This file may be distributed under the terms of the GNU General
# Public License.
#
# LIC: GPL
#
# Usage: pppoe-status [config_file]
# If config_file is omitted, defaults to /etc/ppp/pppoe.conf
#
#***********************************************************************

# Defaults
CONFIG=./pppoe.conf

case "$#" in
    1)
	CONFIG="$1"
	;;
esac

if [ ! -f "$CONFIG" -o ! -r "$CONFIG" ] ; then
    echo "$0: Cannot read configuration file '$CONFIG'" >& 2
    exit 1
fi

. $CONFIG

PPPOE_PIDFILE="$PIDFILE.pppoe"
PPPD_PIDFILE="$PIDFILE.pppd"

if [ "$DEMAND" != "no" ] ; then
    echo "Note: You have enabled demand-connection; pppoe-status may be inaccurate."
fi

# If no PPPOE_PIDFILE, connection is down, unless we're using the Linux plugin
if [ "$LINUX_PLUGIN" = "" ] ; then
    if [ ! -r "$PPPOE_PIDFILE" ] ; then
#	echo "pppoe-status: Link is down (can't read pppoe PID file $PPPOE_PIDFILE)"
	exit 1
    fi
fi

# If no PPPD_PIDFILE, something fishy!
if [ ! -r "$PPPD_PIDFILE" ] ; then
#    echo "pppoe-status: Link is down (can't read pppd PID file $PPPD_PIDFILE)"
    exit 1
fi

PPPD_PID=`cat "$PPPD_PIDFILE"`

# Sigh.  Some versions of pppd put PID files in /var/run; others put them
# in /etc/ppp.  Since it's too messy to figure out what pppd does, we
# try both locations.
for i in /etc/ppp/ppp*.pid /var/run/ppp*.pid ; do
    if [ -r $i ] ; then
	PID=`cat $i`
	if [ "$PID" = "$PPPD_PID" ] ; then
	    IF=`basename $i .pid`
	    cat /proc/net/dev | grep  ${IF} > /dev/null
	    # /sbin/ifconfig $IF | grep "UP.*POINTOPOINT" > /dev/null
	    if [ "$?" != "0" ] ; then
		#echo "pppoe-status: Link is attached to $IF, but $IF is down"
		exit 1
	    fi
	    echo "pppoe-status: Link is up and running on interface $IF" > /dev/null
	    /sbin/ifconfig $IF > /dev/null
		#add by xxj start
		if [ "$CONFIG" = "/fhcfg/pppoe.conf" ] ; then
			echo $IF > /dev/pppoewan0if
		elif [ "$CONFIG" = "/fhcfg/pppoe1.conf" ] ;then
			echo $IF > /dev/pppoewan1if
		elif [ "$CONFIG" = "/fhcfg/pppoe2.conf" ] ;then
			echo $IF > /dev/pppoewan2if
		elif [ "$CONFIG" = "/fhcfg/pppoe3.conf" ] ;then
			echo $IF > /dev/pppoewan3if
		elif [ "$CONFIG" = "/fhcfg/pppoe4.conf" ] ;then
			echo $IF > /dev/pppoebr0if
		elif [ "$CONFIG" = "/fhcfg/pppoe5.conf" ] ;then
			echo $IF > /dev/pppoewan5if
		elif [ "$CONFIG" = "/fhcfg/pppoe6.conf" ] ;then
			echo $IF > /dev/pppoewan6if
		elif [ "$CONFIG" = "/fhcfg/pppoe7.conf" ] ;then
			echo $IF > /dev/pppoewan7if
		elif [ "$CONFIG" = "/fhcfg/pppoe8.conf" ] ;then
			echo $IF > /dev/pppoewan8if
		elif [ "$CONFIG" = "/fhcfg/pppoe9.conf" ] ;then
			echo $IF > /dev/pppoewan9if
		elif [ "$CONFIG" = "/fhcfg/pppoe10.conf" ] ;then
			echo $IF > /dev/pppoewan10if
		elif [ "$CONFIG" = "/fhcfg/pppoesim.conf" ] ;then
			echo $IF > /dev/pppoewansimif
		fi
		#add by xxj end
	    exit 0
	fi
    fi
done

#echo "pppoe-status: Link is down -- could not find interface corresponding to"
#echo "pppd pid $PPPD_PID"
exit 1
